### ISSUE TITLE
*: massive rewrite

### ISSUE THREAD

**Issue by cyphar** [rootless-containers/rootlesscontaine.rs#12]
The original purpose of this website was to simply explain what the idea behind rootless containers was (and the goals of the project). Given that quite a few things are now working we need to include some getting started documentation as well as an explanation of the stack (a diagram of the spec would be very useful as well).

**Comment by AkihiroSuda** [comment]
Any update?

**Comment by cyphar** [comment]
No, this was intended as a tracking issue -- we'd probably need to rewrite the entire thing since the current text is _very_ outdated...

**Comment by AkihiroSuda** [comment]
I know everyone is very busy, but anyone interested in carrying this? ^^

@cyphar @giuseppe

**Comment by AkihiroSuda** [comment]
PR: https://github.com/rootless-containers/rootlesscontaine.rs/pull/19

**Comment by cyphar** [comment]
#19 pretty much covers this now.
