### ISSUE TITLE
No mention of udocker?

### ISSUE THREAD

**Issue by abliss** [rootless-containers/rootlesscontaine.rs#14]
I'm profoundly ignorant about containers so I apologize if this is out of place, but:

I was looking to see how https://github.com/indigo-dc/udocker fits into this space and I was suprised to see no mention of it.

**Comment by AkihiroSuda** [comment]
I think we will cover this through https://github.com/rootless-containers/rootlesscontaine.rs/issues/12

**Comment by cyphar** [comment]
udocker is mentioned now thanks to #19.
