### ISSUE TITLE
consider moving to github wiki

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/rootlesscontaine.rs#16]
Pros:
* easier to contribute for existing maintainers, as it can be modified via a web browser

Cons:
* hard to get new contributors, unless we allows everyone to edit the wiki (likely to get spams), or GitHub wiki supports "pull requests"

**Comment by cyphar** [comment]
I not really in favour of this, mostly because it means that switching hosts will be quite hard. But I do understand the counter-argument (not to mention this project _really_ needs to have a new webpage).

**Comment by AkihiroSuda** [comment]
> because it means that switching hosts will be quite hard

I think `rootlesscontaine.rs` can just have an empty HTML but with `<meta http-equiv=”refresh” content=”0;URL="https://github.com/rootless-containers/rootlesscontaine.rs/wiki" />`
