### ISSUE TITLE
getting-started/common/login/: add a line about `ksu` not setting $XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by dilyanpalauzov** [rootless-containers/rootlesscontaine.rs#44]
https://rootlesscontaine.rs/getting-started/common/login/ says:
> The environmental variable is not set when:
> *  Logged in as the root, and then switched to a non-root user via su -l <user>
> *  Logged in as the root, and then switched to a non-root user via sudo -u <user>

Please add a line 
> * Logged in as the root, and then switched to a non-root user via `ksu <user>`

**Comment by AkihiroSuda** [comment]
Please feel free to open a PR
