### ISSUE TITLE
How does rootless-containers implement the OCI specification?

### ISSUE THREAD

**Issue by oxr463** [rootless-containers/rootlesscontaine.rs#47]
> [OCI Spec](https://github.com/opencontainers/runtime-spec/blob/main/spec.md) seems quite big, which parts are left to implement?

Source: https://github.com/openSUSE/mentoring/issues/160#issuecomment-1086624429

**Comment by AkihiroSuda** [comment]
runc consumes the OCI runtime spec `config.json`, which is generated by Docker/Moby, Podman, containerd, or CRI-O .

e.g., https://github.com/moby/moby/blob/v20.10.14/rootless/specconv/specconv_linux.go

Caveats can be found at https://rootlesscontaine.rs/caveats/
