### ISSUE TITLE
Is `systemd` a hard requirement?

### ISSUE THREAD

**Issue by abitrolly** [rootless-containers/rootlesscontaine.rs#66]
The page https://rootlesscontaine.rs/getting-started/common/ doesn't mention that explicitly, but the https://github.com/containerd/nerdctl/blob/main/docs/rootless.md (which references it) is using https://github.com/containerd/nerdctl/blob/main/extras/rootless/containerd-rootless-setuptool.sh which fails without `systemd`.

Maybe have a chapter about how `systemd` is used, so that people could understand what needs to be done to run rootless containers without it?

Related: https://github.com/containerd/nerdctl/issues/2696

**Comment by AkihiroSuda** [comment]
`containerd-rootless.sh` does not require systemd.

`containerd-rootless-setuptool.sh` is a script to set up systemd units for `containerd-rootless.sh`, so it requires systemd.

**Comment by abitrolly** [comment]
@AkihiroSuda these "systemd units" are files needed to start `containerd` on demand, and on system start up, right?

**Comment by AkihiroSuda** [comment]
Yes only if you want to use systems

Otherwise no

**Comment by abitrolly** [comment]
@AkihiroSuda maybe rename it to from `-setuptool` to `-systemd` https://github.com/containerd/nerdctl/pull/3449 ?

**Comment by abitrolly** [comment]
> Yes only if you want to use systemd
>
> Otherwise no

Is it really possible to run rootless container without `systemd`? It would be nice to update https://github.com/containerd/nerdctl/blob/main/docs/rootless.md to understand what is needed. Does it mean running `containerd` manually?

**Comment by fahedouch** [comment]
Hi @abitrolly, not all cmds need `systemd` for example [no need to init for nsenter](https://github.com/containerd/nerdctl/blob/main/extras/rootless/containerd-rootless-setuptool.sh#L149)

**Comment by fahedouch** [comment]
> @fahedouch hello. Should these helper commands be in `nerdctl` itself?

Yes, for example nerdctl need to nsenter into RootlessKit namespaces (mostly for debugging)
